# Grundläggande statistiska begrepp
Nu när vi fått en introduktion till R behöver vi också titta närmare på några av de statistiska begrepp som redan använts och kommer användas frekvent i detta underlag. 

## Population, stickprov och datainsamling
I ett undersökningsproblem finns det en grupp utav enheter som vi har ett intresse av att dra slutsatser om. Det skulle kunna vara "fiskar i Sverige", "barn mellan 5 till 15 år", "studenter vid LiU" eller "köp vid IKEA". Denna grupp av enheter kallar vi för en <span class="terminology">population</span>. Att samla in information från varje enhet i populationen kommer i många fall vara omöjligt, om inte väldigt dyrt, vilket innebär att vi i praktiken faktiskt inte har möjlighet att dra slutsatser baserat på all information som finns i populationen. 

Istället måste vi förlita oss på en mindre mängd enheter som är en del utav populationen. Denna mindre mängd enheter kan väljas ut på många olika sätt men vi kallar fortfarande mängden för ett <span class="terminology">stickprov</span> eller <span class="terminology">urval</span>. De enheter som specifikt väljs ut ur populationen kommer påverka vilken information som vi samlar in men eftersom vi vill dra slutsatser om populationen är det viktigt att stickprovet speglar populationen, att det är representativt. Att dra slutsatser om storleken på alla fiskar i Sverige baserat på 200 fiskar som undersöktes i Vättern kommer förmodligen inte stämma överens med verkligheten. Det finns en <span class="terminology">bias</span> i detta urval som ger en skev bild av sanningen.

Det vanligaste sättet att genomföra ett urval är genom ett <span class="terminology">Obundet Slumpmässigt Urval</span> (OSU). Denna metod kräver att det finns en förteckning över enheterna i populationen och att varje enhet har samma sannolikhet att bli utvald. Eftersom sannolikheten att bli utvald är samma för vardera enhet kommer denna metod medföra att enheterna är <span class="terminology">oberoende</span>. Detta är en viktig egenskap som vi kommer återkomma till senare.

Kravet på en förteckning av alla enheter i populationen går inte alltid att uppfylla i en undersökning. Att ha en förteckning över alla fiskar i Sverige är förmodligen inget lätt uppdrag och i det tidigare exemplet med fiskarna, var sannolikheten att en fisk i Vättern skulle bli utvald i stickprovet större än 0 medan sannolikheten för en fisk i ett annat vattendrag var 0. Detta är alltså inget OSU i båda bemärkelserna. Istället kan vi använda mer avancerade urvalsmetoder som tar hänsyn till problematiken som uppstår när en förteckning av populationen inte går att utgå ifrån. Mer om detta senare.

## Variabler
När vi valt ut vilka enheter som vi ska samla information från behöver vi också sammanställa dessa mätningar på ett strukturerat sätt. Vi anser att mätningar av samma sak, till exempel arten på fisken, dess vikt och längd, är olika <span class="terminology">variabler</span>. Dessa variabler varierar beroende på vilken enhet som observeras och vi kallar då varje enhets samling av mätvärden för en <span class="terminology">observation</span>. Variabler kan vara av olika typ och följa olika skalor. Dessa egenskaper hjälper till att styra förväntningarna om vad en variabel kan innehålla för information och hur vi kan läsa av den.^[Se [tidigare kapitel](#objectTypes) om typer av objekt i R.] 

### Variabeltyp
Vi delar upp variabeltyper i två huvudsakliga grupper <span class="terminology">kvalitativa</span> och <span class="terminology">kvantitativa</span> variabler. Variabeltypen styr vad vi kan använda för metoder för att sammanfatta, visualisera och analysera informationen.

- Kvalitativa variabler kan beskrivas som kategorier, till exempel arten av en fisk. Det är något som vi mäter i text. Detta motsvarar ett `character`-objekt i R.
- Kvantitativa variabler mäts med siffror, till exempel längden eller vikten av en fisk. Detta motsvarar ett `numeric`-objekt i R.

Om vi samlar in data själv på egen hand, kan vi styra vilken typ av variabel som vi samlar in som mätning av vissa egenskaper. Storleken på en fisk skulle kunna mätas som en kvalitativ variabel, en liten, medelstor eller stor fisk, eller en kvantitativ variabel, vikten angiven i gram, beroende på vad vi vill ha för typ av information. Det är praxis att samla in data kvantitativt om möjligheten finns eftersom vi kan konvertera numeriska mätningar till kategorier i efterhand men vi har ingen möjlighet att konvertera kvalitativa variabler till kvantitativa. Vi kan säga att en fisk som väger 65 g (kvantitativ) är en liten fisk (kvalitativ), men vi kan inte säga hur mycket en liten fisk (kvalitativ) egentligen väger i gram (kvantitativ).

Om vi inte samlar in data själv är ett första steg i analysprocessen att identifiera vilken typ utav variabel som datamaterialet innehåller. 

### Variabelskala
Olika variabler kan följa olika skalor som ger oss information om hur vi relaterar olika värden med varandra. Även denna egenskap styr hur vi kan hantera variablerna i senare delar av undersökningen.

Kvalitativa variabler kan delas in i två olika skalor <span class="terminology">nominal</span>skala och <span class="terminology">ordinal</span>skala. Båda dessa skalor omfattar kategorier (som ibland kan anges med siffror) men det finns en viktig skillnad mellan dem. 

Nominalskala betyder att kategorierna inte går att rangordna på något sätt, att vi inte kan säga att en kategori är större, bättre, eller mer än en annan kategori. Variabeln fiskart följer en sådan skala, vi mäter vilken art en fisk tillhör med en kategor (artens namn), och vi kan inte rangordna art på något sätt.^[Vi kanske kan tycka att vi kan rangordna art utefter dess storlek, sällsynthet, m.m. men då rangordnar vi ju faktiskt efter en annan variabel inte endast art.] 

Ordinalskala däremot innehåller kategorier som vi kan rangordna. Vi kan säga att i den kvalitativa variabeln storlek är "liten" mindre än "medel" *men vi kan inte säga exakt hur mycket mindre*. Ordinalskala kräver inte att skillnaden mellan intilliggande kategorier är lika stora utan bara att det råder en skillnad som kan rangordnas.

Kvantitativa variabler följer huvudsakligen två andra variabelskalor, men det kan förekomma fall där en kvantitativ variabel följer en ordinalskala. Detta kan ske ifall mätningen görs i intervall, 0-4, 5-9, 10-19, osv. och medför att vi kan säga att ett intervall är större än det andra men vi kan inte beräkna exakta skillnader då intervallen är olika stora.

Det vanligaste fallet är däremot att en kvantitativ variabel följer en <span class="terminology">intervall</span>skala eller <span class="terminology">kvot</span>skala. Båda dessa skalor hanterar numeriska värden där vi kan beräkna exakta differenser mellan två olika mätningar men vi kan däremot endast beräkna kvoter i kvotskala.

Ett exempel på intervallskala är temperatur mätt i $^\circ$C. Vi kan säga att 20$^\circ$C är 10 grader varmare än 10$^\circ$C men vi kan **inte** säga att det är dubbelt så varmt. Detta beror på att Celsius-skalan inte har någon tydlig nollpunkt. 0$^\circ$C är egentligen inte 0 i en fysisk betydelse och relationer mellan övriga värden blir då godtyckliga.

Variabler som följer en kvotskala ska ha en absolut nollpunkt, ett värde som faktiskt betyder 0. Längd och vikt är exempel på variabler som följer denna skala då det finns en tydlig nollpunkt som verkligen betyder 0. Vi kan säga att 200g är dubbelt så tungt som 100g.










